export default {
  page: {
    menu: 'Home | Wallet |',
    menu2: 'modify the nickname | Sign out |',
    btn_login: 'Sign in | Sign up | forget the password',
    input_username: 'Phone number |  |',
    file: 'Download The White Paper | 《Interstellar chain user service protocol》 |',
    btn_text: 'Remember me | Forget the password? | I agree',
    btn_text2: 'Return sign in | |',
    btn: 'confirm | submit |',
    wallet: 'Balance | address | transfer',
    wallet2: 'copy | recipient | number',
    wallet3: 'Transaction | income | defray',
    wallet4: 'details | Time | Mode',
    wallet5: 'Number | Status | Address',
    wallet6: 'ID | User statistics | ISC data statistics',
    wallet7: 'circulated | team holding | wait for circulation',
    wallet8: 'The first batch of tokens was 1 billion |  | ',
  },
  message: {
    input_username: 'Please enter the cell phone number | Please enter the correct cell phone number |',
    input_pwassword: 'Please enter the password | Please enter the complete password | Confirm the password',
    input_pwassword2: 'New password | Please enter the password again | The two password input is not consistent, please retype',
    input_code: 'Phone verification code | send code | Please fill in the verification code',
    input_code2: 'Verify sending success | s resend | ',
    agreement: 'Please read the interstellar chain user service agreement | |',
    register: 'register success | modify the password |',
    login:'Sign in success | Do you confirm sign out? |',
    edit: 'nickname | Please set up a new nickname | * up to 10 characters, can be in English, "-" and "_".',
    edit2: 'Please enter the nickname within 10 characters | No transaction record |',
    modal:'Operation hints | Amend the success | * when input is case sensitive, please check the address carefully.'
  },
  text: {
    index_1: 'the creator of the interstellar trade era<br>from the earth to the Milky,to be a witness of the next era',
    index_2: 'Record the auction and transfer of interstellar land with a block chain',
    index_3: 'The time for the wild is past, the time for the interstellar trade era is coming.Interstellar trade will come true in the next 100 years. On the occasion the interstellar trade in land, energy, minerals, and knowledge technology will be common. The low efficiency and high cost of centralization trade currently will become a strong什么路由器能存储器 resistance to interstellar trade. The centralization of block chain technology solves this problem <br><br>The interstellar chain is a decentralized, low-cost and privacy platform based on block chaining technology. It can support large-scale trade accounting among the interstellar, including the auction and transfer of future interstellar land.',
    index_4: 'INTERSTELLAR CHAIN',
    index_5: 'Interstellar chain digitize each element  based on the smallest elements of business (people, things, money)to build a universal link .It creates collaborative activities to reflect real business through different intelligent contracts, and provide relevant value flow tools and systems that match it.Then a new business mode based on this collaborative mode is developed, and a new distributed business ecosystem running on the block chain is constructed step by step.',
    index_6: 'Bottom: | it&#39;s the block chain infrastructure layer. ',
    index_7: 'Middle layer: | it is the second level application interface layer, which implements the data docking of the basic service layer and the business application layer.',
    index_8: 'The upper layer: | it&#39;s the abstraction layer of business application.The standard application module can carry out practical development templates for different business scenarios and different customers, making the final application development, delivery and deployment extremely convenient.',
    index_9: 'Interstellar chain digitize each element  based on the smallest elements of business (people, things, money)to build a universal link .It creates collaborative activities to reflect real business through different intelligent contracts, and provide relevant value flow tools and systems that match it.Then a new business mode based on this collaborative mode is developed, and a new distributed business ecosystem running on the block chain is constructed step by step.',
    index_10: 'The star chain team, headquartered in Hamburg, currently has nearly 130 people (continuous expansion), organized by legend Dr. Aaron who devoted himself to the block chain and digital currency development for 9 years, and Jovian, an investment manager for billions of capital in the financial field, and Noble , a “Wizard “of Internet Design.  | The core members of the team work together for more than 5 years, tacit understanding and stable.The interstellar chain team has an excellent capability from concept, to planning, to product design, to rapid implementation of multi - version technology.',
    index_11: 'Intelligent digital assets, support the account of interstellar mass trade, including the auction and transfer of the future interstellar land',
    index_12: 'Openness | The design of the interstellar chain system is open and transparent, and the public transparency is the cornerstone of the entire interstellar chain system',
    index_13: 'Centralization | No centralization of individuals and organizations can control the entire interstellar chain. it ensures the vitality of the interstellar chain system.',
    index_14: 'Safety | The interstellar chain has enhanced the security mechanism on the basis of the principle of bitcoin development.',
    index_15: 'Consensus mechanism | The interstellar chain improves the DPOS consensus mechanism by adding the concept of the height of the currency block and the heartbeat.',
    index_16: 'superconducting network |  helps a variety of digital assets completely losslessly trade.',
    index_17: 'Intelligent contracts | Automatization controls the transfer of assets.',
    index_18: 'Join the Interstellar chain infrastructure',
    index_19: 'optimize and expand | Create a high quality ecosystem and make a new optimization in the aspects of payment, commerce, investment and other links',
    index_20: 'limited | The present amount of ISC is 1 billion, and the new tokens will be given to the former currency holders by 1:1',
    index_21: 'Open source | Interstellar chain is open source, maintained by the ISC Foundation',
    index_22: 'Knowledge Technology',
    index_23: 'Mineral Resources',
    index_24: 'Energy',
    index_25: 'Land',
    index_26: 'Centralization, Low cost, Privacy',
    index_27: 'The auction and transfer of the future interstellar land',
  }
}
